global using NUnit.Framework;
global using Microsoft.EntityFrameworkCore;
global using PaymentAPI.Data;
global using PaymentAPI.Services;
global using PaymentAPI.Helpers;
global using PaymentAPI.Models.Base;
global using PaymentAPI.Models.Record;
global using PaymentAPI.Models.Request;
global using PaymentAPI.Models.Response;